---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # v3.1.1
        with:
          strict: true
  test:
    strategy:
      matrix:
        target:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a  # master
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab  # v2.7.5

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets --workspace -- -D warnings

      - name: cargo build
        run: cargo build --workspace --all-features

      - name: cargo test
        run: cargo test --all-features --workspace

      - name: cargo doc
        run: cargo doc --document-private-items --no-deps --all-features --workspace

      - name: cargo bench
        run: cargo bench --profile=dev --all-features --workspace -- --test
